name: Release

on:
  release:
    types:
      - created
      - published
      - edited
      - released

jobs:

  release:
    runs-on: ubuntu-18.04

    steps:

      - name: Dump github context
        run: |
          ECHO "Hello World"
